name: Deploy to Kubernetes

on:
  release:
    types: [published]

env:
  APP_NAME: redbot
  APP_IMAGE: ${{ github.repository }}
  REGISTRY: ghcr.io
  HELM_CHARTS_REPOSITORY: RedBoxing/helm-charts

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update the helm chart
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "charts/redbot/values.yaml"
          propertyPath: "image.tag"
          value: ${{github.ref_name}}
          repository: ${{ env.HELM_CHARTS_REPOSITORY }}
          message: "Update ${{github.repository}}'s Image Version to ${{github.ref_name}}"
